version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/usr/src/restful-api/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
    env_file:
      - ./.env
