version: '3'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./app/:/usr/scr/app/"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      FLASK_RUN_HOST: 0.0.0.0


# version: "3.9"
# services:
#   web:
#     build: .
#     ports:
#       - "8000:5000"
#     volumes: 
#       - .:/code
#     environment:
#       FLASK_ENV: development
#   redis:
#     image: "redis:alpine"